// lib/features/academic_hub/academic_curriculum_data.dart
// Comprehensive standard academic curriculum & resources for all Engineering branches and semesters

class AcademicCurriculumData {
  static List<Map<String, dynamic>> getSubjects(String branch, int semester) {
    final b = branch.toUpperCase().trim();
    final s = semester;

    // Common 1st Year (Sem 1 & 2) Curriculum across branches
    if (s == 1) {
      if (b == 'ECE') {
        return [
          {
            'id': 'ece_sem1_ec101',
            'code': 'EC101',
            'name': 'Basic Electronics Engineering',
            'branch': 'ECE',
            'semester': 1,
            'contents': [
              {
                'id': 'ec101_u1',
                'title': 'Unit 1 — Semiconductor Diodes & Applications',
                'contentType': 'NOTES',
                'unit': 1,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/basic_electronics_u1.pdf',
                'uploadedAt': '2026-08-15T10:00:00Z',
              },
              {
                'id': 'ec101_u2',
                'title': 'Unit 2 — Bipolar Junction Transistors (BJT) & Biasing',
                'contentType': 'NOTES',
                'unit': 2,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/basic_electronics_u2.pdf',
                'uploadedAt': '2026-08-16T10:00:00Z',
              },
              {
                'id': 'ec101_u3',
                'title': 'Unit 3 — Field Effect Transistors (FET & MOSFETs)',
                'contentType': 'NOTES',
                'unit': 3,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/basic_electronics_u3.pdf',
                'uploadedAt': '2026-08-17T10:00:00Z',
              },
              {
                'id': 'ec101_u4',
                'title': 'Unit 4 — Operational Amplifiers & Feedback Circuits',
                'contentType': 'CHEAT_SHEET',
                'unit': 4,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/opamps_formulas.pdf',
                'uploadedAt': '2026-08-18T10:00:00Z',
              },
              {
                'id': 'ec101_u5',
                'title': 'Unit 5 — Digital Logic Gates & Boolean Algebra',
                'contentType': 'QUESTION_BANK',
                'unit': 5,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/digital_logic_pyq.pdf',
                'uploadedAt': '2026-08-19T10:00:00Z',
              },
            ],
          },
          {
            'id': 'ece_sem1_ma101',
            'code': 'MA101',
            'name': 'Engineering Mathematics I (Linear Algebra & Calculus)',
            'branch': 'ECE',
            'semester': 1,
            'contents': [
              {
                'id': 'ma101_u1',
                'title': 'Unit 1 — Matrices, Rank & Eigenvalues',
                'contentType': 'NOTES',
                'unit': 1,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/matrices_calculus_u1.pdf',
                'uploadedAt': '2026-08-15T10:00:00Z',
              },
              {
                'id': 'ma101_u2',
                'title': 'Unit 2 — Differential Calculus & Mean Value Theorems',
                'contentType': 'NOTES',
                'unit': 2,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/calculus_u2.pdf',
                'uploadedAt': '2026-08-16T10:00:00Z',
              },
              {
                'id': 'ma101_u3',
                'title': 'Unit 3 — Multivariable Calculus & Partial Derivatives',
                'contentType': 'CHEAT_SHEET',
                'unit': 3,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/maths1_formula_sheet.pdf',
                'uploadedAt': '2026-08-17T10:00:00Z',
              },
              {
                'id': 'ma101_u4',
                'title': 'Unit 4 — Multiple Integrals (Double & Triple)',
                'contentType': 'QUESTION_BANK',
                'unit': 4,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/maths1_solved_papers.pdf',
                'uploadedAt': '2026-08-18T10:00:00Z',
              },
              {
                'id': 'ma101_u5',
                'title': 'Unit 5 — Vector Calculus & Green’s/Stokes’ Theorems',
                'contentType': 'NOTES',
                'unit': 5,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/vector_calculus_u5.pdf',
                'uploadedAt': '2026-08-19T10:00:00Z',
              },
            ],
          },
          {
            'id': 'ece_sem1_ph101',
            'code': 'PH101',
            'name': 'Engineering Physics & Quantum Mechanics',
            'branch': 'ECE',
            'semester': 1,
            'contents': [
              {
                'id': 'ph101_u1',
                'title': 'Unit 1 — Quantum Physics & Wave-Particle Duality',
                'contentType': 'NOTES',
                'unit': 1,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/physics_quantum_u1.pdf',
                'uploadedAt': '2026-08-15T10:00:00Z',
              },
              {
                'id': 'ph101_u2',
                'title': 'Unit 2 — Lasers & Fiber Optics Communication',
                'contentType': 'NOTES',
                'unit': 2,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/fiber_optics_u2.pdf',
                'uploadedAt': '2026-08-16T10:00:00Z',
              },
              {
                'id': 'ph101_u3',
                'title': 'Unit 3 — Dielectric & Magnetic Properties of Materials',
                'contentType': 'NOTES',
                'unit': 3,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/materials_physics_u3.pdf',
                'uploadedAt': '2026-08-17T10:00:00Z',
              },
              {
                'id': 'ph101_u4',
                'title': 'Unit 4 — Superconductivity & Nanomaterials',
                'contentType': 'CHEAT_SHEET',
                'unit': 4,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/physics_formula_handbook.pdf',
                'uploadedAt': '2026-08-18T10:00:00Z',
              },
              {
                'id': 'ph101_u5',
                'title': 'Unit 5 — Ultrasonics & Non-Destructive Testing',
                'contentType': 'QUESTION_BANK',
                'unit': 5,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/physics_pyq_papers.pdf',
                'uploadedAt': '2026-08-19T10:00:00Z',
              },
            ],
          },
          {
            'id': 'ece_sem1_ee101',
            'code': 'EE101',
            'name': 'Basic Electrical Engineering',
            'branch': 'ECE',
            'semester': 1,
            'contents': [
              {
                'id': 'ee101_u1',
                'title': 'Unit 1 — DC Circuits & Network Theorems (KCL/KVL, Thevenin)',
                'contentType': 'NOTES',
                'unit': 1,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/network_theorems_u1.pdf',
                'uploadedAt': '2026-08-15T10:00:00Z',
              },
              {
                'id': 'ee101_u2',
                'title': 'Unit 2 — Single-Phase & 3-Phase AC Circuits',
                'contentType': 'NOTES',
                'unit': 2,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/ac_circuits_u2.pdf',
                'uploadedAt': '2026-08-16T10:00:00Z',
              },
              {
                'id': 'ee101_u3',
                'title': 'Unit 3 — Magnetic Circuits & Single-Phase Transformers',
                'contentType': 'NOTES',
                'unit': 3,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/transformers_u3.pdf',
                'uploadedAt': '2026-08-17T10:00:00Z',
              },
              {
                'id': 'ee101_u4',
                'title': 'Unit 4 — DC Machines & Induction Motors',
                'contentType': 'NOTES',
                'unit': 4,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/dc_machines_u4.pdf',
                'uploadedAt': '2026-08-18T10:00:00Z',
              },
              {
                'id': 'ee101_u5',
                'title': 'Unit 5 — Electrical Installations, Earthing & Safety',
                'contentType': 'QUESTION_BANK',
                'unit': 5,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/electrical_safety_pyq.pdf',
                'uploadedAt': '2026-08-19T10:00:00Z',
              },
            ],
          },
          {
            'id': 'ece_sem1_ec102l',
            'code': 'EC102L',
            'name': 'Basic Electronics & Devices Laboratory',
            'branch': 'ECE',
            'semester': 1,
            'contents': [
              {
                'id': 'ec102l_m1',
                'title': 'Complete Lab Manual — Experiments 1 to 10 (VI Characteristics, Rectifiers, Op-Amps)',
                'contentType': 'LAB_MANUAL',
                'unit': 1,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/ece_lab_manual_sem1.pdf',
                'uploadedAt': '2026-08-20T10:00:00Z',
              },
              {
                'id': 'ec102l_v1',
                'title': 'Lab Viva Voce & Practical Exam Question Bank',
                'contentType': 'QUESTION_BANK',
                'unit': 2,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/ece_lab_viva_questions.pdf',
                'uploadedAt': '2026-08-21T10:00:00Z',
              },
            ],
          },
        ];
      }

      if (b == 'CSE' || b == 'AI_ML') {
        return [
          {
            'id': 'cse_sem1_cs101',
            'code': 'CS101',
            'name': 'Problem Solving & Programming in C/Python',
            'branch': b,
            'semester': 1,
            'contents': [
              {
                'id': 'cs101_u1',
                'title': 'Unit 1 — Algorithms, Flowcharts & Control Flow',
                'contentType': 'NOTES',
                'unit': 1,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/c_programming_u1.pdf',
                'uploadedAt': '2026-08-15T10:00:00Z',
              },
              {
                'id': 'cs101_u2',
                'title': 'Unit 2 — Arrays, Strings & Modular Functions',
                'contentType': 'NOTES',
                'unit': 2,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/c_arrays_functions_u2.pdf',
                'uploadedAt': '2026-08-16T10:00:00Z',
              },
              {
                'id': 'cs101_u3',
                'title': 'Unit 3 — Pointers & Dynamic Memory Allocation',
                'contentType': 'NOTES',
                'unit': 3,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/pointers_memory_u3.pdf',
                'uploadedAt': '2026-08-17T10:00:00Z',
              },
              {
                'id': 'cs101_u4',
                'title': 'Unit 4 — Structures, Unions & Bitwise Operators',
                'contentType': 'CHEAT_SHEET',
                'unit': 4,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/c_structures_cheatsheet.pdf',
                'uploadedAt': '2026-08-18T10:00:00Z',
              },
              {
                'id': 'cs101_u5',
                'title': 'Unit 5 — File Handling & Preprocessor Directives',
                'contentType': 'QUESTION_BANK',
                'unit': 5,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/c_programming_pyq.pdf',
                'uploadedAt': '2026-08-19T10:00:00Z',
              },
            ],
          },
          {
            'id': 'cse_sem1_ma101',
            'code': 'MA101',
            'name': 'Engineering Mathematics I (Linear Algebra & Calculus)',
            'branch': b,
            'semester': 1,
            'contents': [
              {
                'id': 'ma101_cse_u1',
                'title': 'Unit 1 — Linear Equations, Matrices & Rank',
                'contentType': 'NOTES',
                'unit': 1,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/matrices_calculus_u1.pdf',
                'uploadedAt': '2026-08-15T10:00:00Z',
              },
              {
                'id': 'ma101_cse_u2',
                'title': 'Unit 2 — Differential Calculus & Taylor Series',
                'contentType': 'NOTES',
                'unit': 2,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/calculus_u2.pdf',
                'uploadedAt': '2026-08-16T10:00:00Z',
              },
              {
                'id': 'ma101_cse_u3',
                'title': 'Unit 3 — Partial Derivatives & Maxima-Minima',
                'contentType': 'CHEAT_SHEET',
                'unit': 3,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/maths1_formula_sheet.pdf',
                'uploadedAt': '2026-08-17T10:00:00Z',
              },
              {
                'id': 'ma101_cse_u4',
                'title': 'Unit 4 — Double & Triple Integrals',
                'contentType': 'QUESTION_BANK',
                'unit': 4,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/maths1_solved_papers.pdf',
                'uploadedAt': '2026-08-18T10:00:00Z',
              },
              {
                'id': 'ma101_cse_u5',
                'title': 'Unit 5 — Gradient, Divergence & Curl Vector Calculus',
                'contentType': 'NOTES',
                'unit': 5,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/vector_calculus_u5.pdf',
                'uploadedAt': '2026-08-19T10:00:00Z',
              },
            ],
          },
          {
            'id': 'cse_sem1_ec101',
            'code': 'EC101',
            'name': 'Digital Electronics & Logic Design',
            'branch': b,
            'semester': 1,
            'contents': [
              {
                'id': 'ec101_cse_u1',
                'title': 'Unit 1 — Number Systems, Boolean Algebra & K-Maps',
                'contentType': 'NOTES',
                'unit': 1,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/digital_logic_u1.pdf',
                'uploadedAt': '2026-08-15T10:00:00Z',
              },
              {
                'id': 'ec101_cse_u2',
                'title': 'Unit 2 — Combinational Circuits (Adders, Multiplexers, Decoders)',
                'contentType': 'NOTES',
                'unit': 2,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/combinational_circuits_u2.pdf',
                'uploadedAt': '2026-08-16T10:00:00Z',
              },
              {
                'id': 'ec101_cse_u3',
                'title': 'Unit 3 — Sequential Circuits (Latches, Flip-Flops & Counters)',
                'contentType': 'NOTES',
                'unit': 3,
                'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/sequential_circuits_u3.pdf',
                'uploadedAt': '2026-08-17T10:00:00Z',
              },
            ],
          },
        ];
      }
    }

    // Default Fallback Subjects for any Branch & Semester
    return [
      {
        'id': '${b.toLowerCase()}_sem${s}_core1',
        'code': '$b${s}01',
        'name': '$b Core Engineering Theory $s',
        'branch': b,
        'semester': s,
        'contents': [
          {
            'id': '${b.toLowerCase()}_sem${s}_u1',
            'title': 'Unit 1 — Foundations, Architecture & Fundamental Principles',
            'contentType': 'NOTES',
            'unit': 1,
            'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/engineering_core_u1.pdf',
            'uploadedAt': '2026-08-15T10:00:00Z',
          },
          {
            'id': '${b.toLowerCase()}_sem${s}_u2',
            'title': 'Unit 2 — Analysis, Design & Mathematical Modeling',
            'contentType': 'NOTES',
            'unit': 2,
            'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/engineering_core_u2.pdf',
            'uploadedAt': '2026-08-16T10:00:00Z',
          },
          {
            'id': '${b.toLowerCase()}_sem${s}_u3',
            'title': 'Unit 3 — Implementation, Optimization & Real-World Case Studies',
            'contentType': 'CHEAT_SHEET',
            'unit': 3,
            'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/engineering_formulas_u3.pdf',
            'uploadedAt': '2026-08-17T10:00:00Z',
          },
          {
            'id': '${b.toLowerCase()}_sem${s}_u4',
            'title': 'Unit 4 — Previous 5 Years Solved Exam Questions & Model Papers',
            'contentType': 'QUESTION_BANK',
            'unit': 4,
            'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/engineering_solved_pyq.pdf',
            'uploadedAt': '2026-08-18T10:00:00Z',
          },
        ],
      },
      {
        'id': '${b.toLowerCase()}_sem${s}_core2',
        'code': '$b${s}02',
        'name': 'Applied $b Systems & Computing ($s)',
        'branch': b,
        'semester': s,
        'contents': [
          {
            'id': '${b.toLowerCase()}_sem${s}_sys_u1',
            'title': 'Unit 1 — System Architecture, Modules & State Representations',
            'contentType': 'NOTES',
            'unit': 1,
            'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/system_computing_u1.pdf',
            'uploadedAt': '2026-08-15T10:00:00Z',
          },
          {
            'id': '${b.toLowerCase()}_sem${s}_sys_u2',
            'title': 'Unit 2 — Simulation, Verification & Industry Standard Protocols',
            'contentType': 'NOTES',
            'unit': 2,
            'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/system_computing_u2.pdf',
            'uploadedAt': '2026-08-16T10:00:00Z',
          },
        ],
      },
      {
        'id': '${b.toLowerCase()}_sem${s}_lab',
        'code': '$b${s}03L',
        'name': '$b Laboratory & Experimental Practicum',
        'branch': b,
        'semester': s,
        'contents': [
          {
            'id': '${b.toLowerCase()}_sem${s}_lab_m',
            'title': 'Complete Practical Lab Manual & Experiments Handout',
            'contentType': 'LAB_MANUAL',
            'unit': 1,
            'fileUrl': 'https://myvault-files-app.s3.eu-north-1.amazonaws.com/notes/lab_manual_practicum.pdf',
            'uploadedAt': '2026-08-20T10:00:00Z',
          },
        ],
      },
    ];
  }
}
